export const TOGGLE_OPERATION_LIST_SHOW = 'operation/TOGGLE_OPERATION_LIST_SHOW'
export const CHANGE_OPERATION_TYPE = 'operation/CHANGE_OPERATION_TYPE'
export const CHANGE_OPERATION_SONG_ID = 'operation/CHANGE_OPERATION_SONG_ID'
export const CHANGE_OPERATION_SINGERS_LIST = 'operation/CHANGE_OPERATION_SINGERS_LIST'
